spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hsm1@138
    url: jdbc:mysql://localhost:3306/MSversion
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 5775