spring:
  application:
    name: version-gateway
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Hsm1@138
#    url: jdbc:mysql://localhost:3306/MSversion
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: houshengming
    url: jdbc:mysql://39.104.112.98:5775/MSversion
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    gateway:
      routes:
        - id: route
          order: 0
          uri: lb://service
          predicates:
            - Path=/service/**
    nacos:
      discovery:
        server-addr: 39.104.112.98:8848
        namespace: public
        username: nacos
        password: nacos
server:
  port: 5678
